syntax = "proto3";
package rpcpb;
option go_package = "github.com/portbuster1337/arachne-c2/protobuf/rpcpb";

import "commonpb/common.proto";
import "arachnepb/arachne.proto";

service ArachneRPC {
  // Operator management
  rpc GetVersion(commonpb.Empty) returns (Version);
  rpc GetImplants(commonpb.Empty) returns (ImplantList);

  // Implant interactions
  rpc Kill(arachnepb.KillReq) returns (commonpb.Empty);
  rpc Ps(arachnepb.PsReq) returns (arachnepb.Ps);
  rpc Execute(arachnepb.ExecuteReq) returns (arachnepb.Execute);
  rpc Ls(arachnepb.LsReq) returns (arachnepb.Ls);
  rpc Pwd(arachnepb.PwdReq) returns (arachnepb.Pwd);
  rpc Download(arachnepb.DownloadReq) returns (arachnepb.Download);
  rpc Upload(arachnepb.UploadReq) returns (arachnepb.Upload);
  rpc Screenshot(arachnepb.ScreenshotReq) returns (arachnepb.Screenshot);

  // Session interactions
  rpc Shell(arachnepb.ShellReq) returns (arachnepb.Shell);
  rpc TunnelData(stream arachnepb.TunnelData) returns (stream arachnepb.TunnelData);
  rpc CreateSocks(arachnepb.Socks) returns (arachnepb.Socks);
  rpc SocksProxy(stream arachnepb.SocksData) returns (stream arachnepb.SocksData);
}

message Version {
  string Version = 1;
  string Commit = 2;
  string GoVersion = 3;
}

message ImplantInfo {
  string ID = 1;
  string Name = 2;
  string Hostname = 3;
  string OS = 4;
  string Arch = 5;
  string Username = 6;
  string PeerID = 7;
  int64 LastCheckin = 8;
  int64 Interval = 9;
  bool IsBeacon = 10;
  string Locale = 11;
  string RemoteAddress = 12;
}

message ImplantList {
  repeated ImplantInfo Implants = 1;
}
